resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 5
      minimumNumberOfCalls: 1
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      slidingWindowType: TIME_BASED
      failureRateThreshold: 99
      recordExceptions:
        - org.springframework.web.client.ResourceAccessException
        - org.springframework.web.client.HttpServerErrorException
        - org.springframework.web.client.HttpStatusCodeException
        - org.springframework.web.client.RestClientResponseException
        - org.springframework.web.client.RestClientException
        - org.springframework.core.NestedRuntimeException
        - java.lang.RuntimeException
  backends:
    nameService:
      baseConfig: default
