spring:
  application:
    name: greeting
server:
  port: 8080
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 8
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 1s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.ResourceAccessException
        - org.springframework.web.client.HttpServerErrorException
        - org.springframework.web.client.HttpStatusCodeException
        - org.springframework.web.client.RestClientResponseException
        - org.springframework.web.client.RestClientException
        - org.springframework.core.NestedRuntimeException
        - java.lang.RuntimeException
  instances:
    nameService:
      baseConfig: default
